[update]
#tasks = ["interfaces", "transform", "normalize"]
tasks = ["normalize"]

[update.interfaces]
path = "ErgoStack"
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false

[update.transform]
codePath = "ErgoStack"
localizablePath = "ErgoStack"
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
path = "ErgoStack"
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
path = "ErgoStack"
duplicateKeys = true
emptyValues = true

