[update]
tasks = ["normalize"]

[update.normalize]
path = "ErgoStack"
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
path = "ErgoStack"
duplicateKeys = true
emptyValues = true

