excluded:
  - .idea
  - Pods
  - fastlane
  - ErgoStack/R.generated.swift

disabled_rules:
  - file_header
  - todo
  - force_cast
  - force_try
  - xctfail_message
  - line_length
  - multiple_closures_with_trailing_closure # incompatible with SwiftUI

analyzer_rules:
- unused_import
- unused_declaration

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_object_literal
#  - empty_count
  - extension_access_modifier
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicit_return
#  - implicitly_unwrapped_optional
  - joined_default_parameter
#  - let_var_whitespace # incompatible with Property Wrappers
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
#  - no_grouping_extension
#  - number_separator
#  - object_literal
#  - operator_usage_whitespace
  - override_in_extension
  - overridden_super_call
  - pattern_matching_keywords
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - required_enum_case
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
#  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
# addon rules from swiftlint:
  - anyobject_protocol
  - collection_alignment
  - empty_string
  - empty_xctest_method
  - fallthrough
  - file_name
  - identical_operands
  - last_where
  - lower_acl_than_parent
#  - private_action
#  - private_outlet # - unable to make test
#  - prohibited_interface_builder
  - redundant_type_annotation
  - single_test_class
  - static_operator
  - unavailable_function
  - untyped_error_in_catch
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - type_name
  - type_body_length
  - file_length
  - identifier_name
  - cyclomatic_complexity
  - function_parameter_count
  - reduce_into
#  - file_types_order
  - type_contents_order # incompatible with SwiftUI
  - unowned_variable_capture
  - duplicate_enum_cases
  - legacy_multiple
  - convenience_type
  - modifier_order
  - toggle_bool
  - unused_private_declaration
  - contains_over_range_nil_comparison
  - flatmap_over_map_reduce
  - raw_value_for_camel_cased_codable_enum
  - enum_case_associated_value_count
  - optional_enum_case_matching
  - prefer_self_type_over_type_of_self
  - custom_rules

trailing_comma:
  mandatory_comma: true

#line_length:
#  warning: 150
#  error: 250
#  ignore_comments: true

trailing_whitespace:
  ignores_empty_lines: true # consider removing this - wordpress suppresses removing all

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
# line_length: 110
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded:
    - iPhone # excluded via string
    - API
    - Tag
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    - API
    - v1
    - up

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)

cyclomatic_complexity:
  warning: 30
  error: 50

function_parameter_count:
  warning: 7
  error: 11

unused_declaration:
  include_public_and_open: true

# from wordpress iOS
control_statement:
  severity: error

custom_rules:

  natural_content_alignment:
    name: "Natural Content Alignment"
    regex: '\.contentHorizontalAlignment(\s*)=(\s*)(\.left|\.right)'
    message: "Forcing content alignment left or right can affect the Right-to-Left layout. Use naturalContentHorizontalAlignment instead."
    severity: warning

  natural_text_alignment:
    name: "Natural Text Alignment"
    regex: '\.textAlignment(\s*)=(\s*).left'
    message: "Forcing text alignment to left can affect the Right-to-Left layout. Consider setting it to `natural`"
    severity: warning

  inverse_text_alignment:
    name: "Inverse Text Alignment"
    regex: '\.textAlignment(\s*)=(\s*).right'
    message: "When forcing text alignment to the right, be sure to handle the Right-to-Left layout case properly, and then silence this warning with this line `// swiftlint:disable:next inverse_text_alignment`"
    severity: warning

  localization_comment:
    name: "Localization Comment"
    regex: 'NSLocalizedString([^,]+,\s+comment:\s*"")'
    message: "Localized strings should include a description giving context for how the string is used."
    severity: warning

  string_interpolation_in_localized_string:
    name: "String Interpolation in Localized String"
    regex: 'NSLocalizedString\("[^"]*\\\(\S*\)'
    message: "Localized strings must not use interpolated variables. Instead, use `String(format:`"
    severity: error
